export const sampleData = [
  {
    title: "롯데프리미엄아울렛 동부산점",
    locationGubun: "쇼핑",
    mbti: ["ESVF", "EOVF", "CSVF", "CSVB"],
    holiday: null,
  },
  {
    title: "몽작",
    locationGubun: "식당",
    mbti: "all",
    holiday: null,
  },
  {
    title: "부산시민공원",
    locationGubun: "공원",
    mbti: "all",
    holiday: null,
  },
  {
    title: "센텀 APEC나루공원",
    locationGubun: "공원",
    mbti: ["ESVF", "EOVF", "ENVF", "EOVB"],
    holiday: null,
  },
  {
    title: "신호공원",
    locationGubun: "공원",
    mbti: ["CSVF", "CSVB", "CSNF", "CSNB"],
    holiday: null,
  },
  {
    title: "오르디",
    locationGubun: "카페",
    mbti: ["CSVF", "ENVF", "EOVF", "CSVB"],
    holiday: null,
  },
  {
    title: "온천천시민공원",
    locationGubun: "공원",
    mbti: "all",
    holiday: null,
  },
  {
    title: "칠암만장",
    locationGubun: "식당",
    mbti: "all",
    holiday: "월요일",
  },
  {
    title: "카페 만디",
    locationGubun: "카페",
    mbti: ["ENVF", "EOVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "포레스트3002",
    locationGubun: "브런치",
    mbti: "all",
    holiday: "화요일",
  },
  {
    title: "홍법사(부산)",
    locationGubun: "사찰",
    mbti: ["CSVF", "CSVB", "CSNF", "CSNB"],
    holiday: null,
  },
  {
    title: "감나무집",
    locationGubun: "식당",
    mbti: ["CSVF", "CSVB", "ESVF", "ESVB"],
    holiday: null,
  },
  {
    title: "구덕포끝집고기",
    locationGubun: "식당",
    mbti: ["ESVF", "EOVF", "CSVF", "ENVF"],
    holiday: null,
  },
  {
    title: "그림하우스",
    locationGubun: "카페",
    mbti: ["ENVF", "CSVF", "EOVF", "ESVF"],
    holiday: null,
  },
  {
    title: "대보름",
    locationGubun: "식당",
    mbti: "all",
    holiday: null,
  },
  {
    title: "대저생태공원",
    locationGubun: "공원",
    mbti: "all",
    holiday: null,
  },
  {
    title: "대저수문 생태공원",
    locationGubun: "공원",
    mbti: ["ENVF", "EOVF", "CSVF", "CSNF"],
    holiday: null,
  },
  {
    title: "더웨이브",
    locationGubun: "카페",
    mbti: ["EOVF", "ENVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "덕미",
    locationGubun: "식당",
    mbti: ["CSVF", "CSVB", "ESVF", "ESVB"],
    holiday: null,
  },
  {
    title: "듀스포레",
    locationGubun: "카페",
    mbti: ["ENVF", "EOVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "만달리",
    locationGubun: "식당",
    mbti: "all",
    holiday: null,
  },
  {
    title: "맥도생태공원",
    locationGubun: "공원",
    mbti: "all",
    holiday: null,
  },
  {
    title: "모닝듀 게스트 하우스(모닝듀)",
    locationGubun: "숙소",
    mbti: ["EOVF", "ENVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "무명일기",
    locationGubun: "카페",
    mbti: ["CSVF", "ENVF", "EOVF", "CSVB"],
    holiday: null,
  },
  {
    title: "불란서그로서리",
    locationGubun: "카페",
    mbti: ["ENVF", "EOVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "브리타니",
    locationGubun: "카페",
    mbti: ["ENVF", "EOVF", "CSVF", "ESVF"],
    holiday: null,
  },
  {
    title: "비아조",
    locationGubun: "식당",
    mbti: ["EOVF", "ENVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "성안집",
    locationGubun: "식당",
    mbti: ["CSVF", "CSVB", "ESVF", "ESVB"],
    holiday: null,
  },
  {
    title: "송정물총칼국수",
    locationGubun: "식당",
    mbti: "all",
    holiday: null,
  },
  {
    title: "스노잉클라우드",
    locationGubun: "카페",
    mbti: ["ENVF", "EOVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "알로이삥삥",
    locationGubun: "카페",
    mbti: ["EOVF", "ENVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "오구카페",
    locationGubun: "카페",
    mbti: ["ENVF", "EOVF", "CSVF", "ESVF"],
    holiday: null,
  },
  {
    title: "웨스턴챔버",
    locationGubun: "카페",
    mbti: ["EOVF", "ENVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "웨이브온 커피",
    locationGubun: "카페",
    mbti: ["ENVF", "EOVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "윙민박",
    locationGubun: "숙소",
    mbti: ["CSVF", "CSVB", "ESVF", "ESVB"],
    holiday: null,
  },
  {
    title: "유정1995 기장 본점",
    locationGubun: "식당",
    mbti: ["EOVF", "ENVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "을숙도 공원",
    locationGubun: "공원",
    mbti: "all",
    holiday: null,
  },
  {
    title: "이바구캠프",
    locationGubun: "숙소",
    mbti: ["ENVF", "EOVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "카페베이스",
    locationGubun: "카페",
    mbti: ["ENVF", "EOVF", "CSVF", "ESVF"],
    holiday: null,
  },
  {
    title: "팝콘 호스텔 해운대점",
    locationGubun: "숙소",
    mbti: ["EOVF", "ENVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "프루터리포레스트",
    locationGubun: "카페",
    mbti: ["ENVF", "EOVF", "CSVF", "ESVF"],
    holiday: null,
  },
  {
    title: "해월전망대",
    locationGubun: "레저",
    mbti: ["ENVF", "EOVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "형제가든",
    locationGubun: "식당",
    mbti: "all",
    holiday: null,
  },
  {
    title: "황령산",
    locationGubun: "레저",
    mbti: "all",
    holiday: null,
  },
  {
    title: "황령산 전망대",
    locationGubun: "레저",
    mbti: "all",
    holiday: null,
  },
  {
    title: "황령산레포츠공원",
    locationGubun: "레저",
    mbti: "all",
    holiday: null,
  },
  {
    title: "회동수원지",
    locationGubun: "공원",
    mbti: "all",
    holiday: null,
  },
  {
    title: "회동수원지 둘레길",
    locationGubun: "레저",
    mbti: "all",
    holiday: null,
  },
  {
    title: "AJ하우스(AJ House)",
    locationGubun: "숙소",
    mbti: ["EOVF", "ENVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "EL16.52",
    locationGubun: "카페",
    mbti: ["ENVF", "EOVF", "CSVF", "ESVF"],
    holiday: null,
  },
  {
    title: "JSTAY",
    locationGubun: "숙소",
    mbti: ["EOVF", "ENVF", "ESVF", "CSVF"],
    holiday: null,
  },
  {
    title: "The Park Guest House",
    locationGubun: "숙소",
    mbti: ["ENVF", "EOVF", "ESVF", "CSVF"],
    holiday: null,
  },
];
